Show player details for match lineups
flashkillapp/flashkill pull request #76
Opened 2021-11-09 22:28 UTC by timonla

![image](https://user-images.githubusercontent.com/4618507/141015555-7a02e5da-053e-4640-a1ae-90698798ea5b.png)

Resolves #57

2021-11-10 14:21 UTC, Lyannic commented
Do we really want to mirror the table for the other team?

2021-11-10 15:00 UTC, Lyannic requested changes

2021-11-10 21:11 UTC, timonla commented on src/components/FaceitLogo.ts
> +  @property({ type: Object }) faceitInfo!: FaceitInfo;
Fixed it

2021-11-10 21:12 UTC, timonla commented on src/components/LineupTables.ts
> +            .renderer="${this.nameRenderer}"
Decided to go with a non-mirrored version, as you suggested in another comment. Was able to reuse the table creation like that.

![image](https://user-images.githubusercontent.com/4618507/141194131-8766c840-25fb-4e13-8b84-91d8fe0090b5.png)

2021-11-11 11:53 UTC, Lyannic approved these changes

2021-11-11 11:53 UTC, Lyannic commented on src/components/LineupTables.ts
> +export interface LineupTableItem {
You don't need to change this, just a remark. I don't like the technical naming that you apply here. A lineup probably consists of players or something like that. You are also using very technical names for the props (`lineupItems1`). What I would expect, is just a lineup. So `lineup1` and `lineup2` as props.

2021-11-11 16:07 UTC, merged